name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  # - jupyterlab=3.0.12
  - jupyter=1.0.0  # https://knowledge.udacity.com/questions/894765
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - jinja2=3.0.3  # https://knowledge.udacity.com/questions/821482#822258
  - pip:
      - wandb==0.12.17 #https://knowledge.udacity.com/questions/854897